### ISSUE TITLE
credenciais para os bancos de dados

### ISSUE THREAD

**Issue by pauloFernandes** [viniqrz/raro-mailer#32]
seguem abaixo as credenciais para os bancos de dados que poderão ser utilizados no trabalho final. O banco `_prod` será o avaliado na entrega do projeto.

```yaml
host: 3.221.159.196
port: 3320
user: 'high_five_user'
password: '869QkEHJcyQfPL55'
databases:
  high_five_inventario_dev
  high_five_inventario_hml
  high_five_inventario_prod
```
